### ISSUE TITLE
broken iframes on projects page

### ISSUE THREAD

**Issue by timurb** [moby/mobywebsite#17]
<img width="1022" alt="image 2017-06-27 at 7 32 41 pm" src="https://user-images.githubusercontent.com/209945/27598862-8300355c-5b6f-11e7-81ab-dc76db3833fa.png">

**Comment by chanezon** [comment]
Fixed by https://github.com/moby/mobywebsite/pull/18 I added a Jekyll plugin that renders all projects and profiles inline on the server side, and @jsouth styled them.
