### ISSUE TITLE
Question: criteria of docs/_data/contributors.yml ?

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/mobywebsite#33]
https://github.com/moby/mobywebsite/blob/dde41bd87e537b7138cf462bf72ec51eb86f762c/docs/_data/contributors.yml looks randomly(?) picked names of the maintainers, but the criteria is not clear.

@moby/mobywebsite @thaJeztah

**Comment by thaJeztah** [comment]
good question. @chanezon ?

**Comment by AkihiroSuda** [comment]
ping @chanezon
