### ISSUE TITLE
Moby website is not showing properly

### ISSUE THREAD

**Issue by dungeonmaster18** [moby/mobywebsite#36]
![screenshot-2017-12-23 moby](https://user-images.githubusercontent.com/23421535/34320333-f447aa70-e81d-11e7-94ee-dcef0567a67f.png)

**Comment by thaJeztah** [comment]
ping @chanezon

**Comment by chanezon** [comment]
It is fixed now!

**Comment by thaJeztah** [comment]
Thanks!
