### ISSUE TITLE
Add a blog to the site

### ISSUE THREAD

**Issue by amirmc** [moby/mobywebsite#4]
I'm working on this in a local branch and a rough first cut is ready but I'm having issues settling on a URL schema. Mainly because the autogenerated urls are either of the form `YYYY/MM/DD/<post-title>` (which is annoying to copy/paste/share) or `blog/<post-title>` which doesn't work well if you have many posts with the same title (e.g. the weekly dev reports).

**Comment by chanezon** [comment]
I'd vote for YYYY/MM/DD/<post-title> which is a classic way of avoiding post name conflicts, and conveys date info in the url.
The Docker blog uses YYYY/MM/<post-title> but that may create conflicts for weekly dev reports.

For Atom feed https://help.github.com/articles/atom-rss-feeds-for-github-pages/

**Comment by chanezon** [comment]
Thank you @amirmc, merged!
