### ISSUE TITLE
The link to README is dead

### ISSUE THREAD

**Issue by ghost** [moby/mobywebsite#45]
https://github.com/moby/mobywebsite/blob/3105de0b2cfb0bc8ba4011aea553823b78b72baa/docs/_includes/links.html#L3

Current value:
https://github.com/moby/moby/blob/moby/README.md
Expected value:
https://github.com/moby/moby/blob/master/README.md

Because there is no moby branch.

**Comment by crydotsnake** [comment]
I created a PR to fix that: https://github.com/moby/mobywebsite/pull/49

**Comment by sam-thibault** [comment]
Fixed by #71
